server:
  port: 7654

spring:
  # 上传配置
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  # redis 配置
  redis:
    host: 192.168.1.101
    password: pubgM666
    port: 6379
    database: 2
  # mail 配置
  mail:
    host: smtp.gmail.com
    port: 587
    username: iamkevinkd@gmail.com
    password: srdlgzhxofwanikw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # mysql 配置
  datasource:
    url: jdbc:mysql://172.24.192.134:3306/file_sys?serverTimezone=UTC
    username: jasper
    password: pubgM666
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# minio 配置
minio:
  endpoint: http://192.168.1.101:9000
  access-key: BdsOyQdaT1cMM6lojeoC
  secret-key: Pxd2Dkp9XC1MQ5lRxc3cKuVm8AyKnoOapcSIGZea

# jwt
jwt:
  secret: asdhugjasdNDUYGasdh-aSDHGd47bd1D